### ISSUE TITLE
Picasso detected an unsupported OkHttp on the classpath

### ISSUE THREAD

**Issue by escobar5** [jacksierkstra/Picasso#5]
I'm trying to use this library in Xamarin Android but I get this error:

Java.Lang.RuntimeException: Picasso detected an unsupported OkHttp on the classpath.
To use OkHttp with this version of Picasso, you'll need:
1. com.squareup.okhttp:okhttp:1.6.0 (or newer)
2. com.squareup.okhttp:okhttp-urlconnection:1.6.0 (or newer)
Note that OkHttp 2.0.0+ is supported!
  at at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <IL 0x00011, 0x00068>
  at Android.Runtime.JNIEnv.CallStaticObjectMethod (intptr,intptr,Android.Runtime.JValue[]) [0x00064] in /Users/builder/data/lanes/monodroid-mlion-monodroid-4.21-series/38ac51a9/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:1161
  at Com.Squareup.Picasso.Picasso.With (Android.Content.Context) [0x0002a] in \\psf\home\Documents\Visual Studio 2013\Projects\Picasso.Net\Picasso.Net\obj\Release\generated\src\Com.Squareup.Picasso.Picasso.cs:1537
  at Q10.Jack.Mobile.Droid.NewsAdapter.CreateThumbnail (string[],int) [0x00097] in c:\Proyectos\Q10\Versiones\Q10.Jack.Mobile\Droid\Adapters\NewsAdapter.cs:81
  at Q10.Jack.Mobile.Droid.NewsAdapter/<>c__DisplayClass8.<OnBindViewHolder>b__6 (string,int) [0x00000] in c:\Proyectos\Q10\Versiones\Q10.Jack.Mobile\Droid\Adapters\NewsAdapter.cs:105
  at at System.Linq.Enumerable/<CreateSelectIterator>c__Iterator11`2<string, Android.Widget.ImageView>.MoveNext () <0x002e3>
  at at System.Collections.Generic.List`1<Android.Widget.ImageView>.AddEnumerable (System.Collections.Generic.IEnumerable`1<Android.Widget.ImageView>) <0x0018f>
  at at System.Collections.Generic.List`1<Android.Widget.ImageView>..ctor (System.Collections.Generic.IEnumerable`1<Android.Widget.ImageView>) <0x0015b>
  at at System.Linq.Enumerable.ToList<Android.Widget.ImageView> (System.Collections.Generic.IEnumerable`1<Android.Widget.ImageView>) <0x00077>
  at NewsAdapter.OnBindViewHolder (Android.Support.V7.Widget.RecyclerView/ViewHolder,int) [0x000fd] in \NewsAdapter.cs:105
  at at Android.Support.V7.Widget.RecyclerView/Adapter.n_OnBindViewHolder_Landroid_support_v7_widget_RecyclerView_ViewHolder_I (intptr,intptr,intptr,int) <IL 0x00014, 0x000f7>
  at at (wrapper dynamic-method) object.d615c9a5-5d0e-4729-b9e7-6df61fed9470 (intptr,intptr,intptr,int) <IL 0x0001d, 0x0004b>
  at --- End of managed exception stack trace ---
  at java.lang.RuntimeException: Picasso detected an unsupported OkHttp on the classpath.
  at To use OkHttp with this version of Picasso, you'll need:
  at 1. com.squareup.okhttp:okhttp:1.6.0 (or newer)
  at 2. com.squareup.okhttp:okhttp-urlconnection:1.6.0 (or newer)
  at Note that OkHttp 2.0.0+ is supported!
  at at com.squareup.picasso.Utils.createDefaultDownloader(Utils.java:251)
  at at com.squareup.picasso.Picasso$Builder.build(Picasso.java:754)
  at at com.squareup.picasso.Picasso.with(Picasso.java:597)
  at at NewsAdapter.n_onBindViewHolder(Native Method)
  at at  NewsAdapter.onBindViewHolder(NewsAdapter.java:47)
  at at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:4138)
  at at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3448)
  at at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3340)
  at at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1810)
  at at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1306)
  at at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1269)
  at at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:523)
  at at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:1988)
  at at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2237)
  at at android.view.View.layout(View.java:15596)
  at at android.view.ViewGroup.layout(ViewGroup.java:4966)
  at at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:543)
  at at android.view.View.layout(View.java:15596)
  at at android.view.ViewGroup.layout(ViewGroup.java:4966)
  at at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
  at at android.view.View.layout(View.java:15596)
  at at android.view.ViewGroup.layout(ViewGroup.java:4966)
  at at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
  at at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
  at at android.view.View.layout(View.java:15596)
  at at android.view.ViewGroup.layout(ViewGroup.java:4966)
  at at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
  at at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
  at at android.view.View.layout(View.java:15596)
  at at android.view.ViewGroup.layout(ViewGroup.java:4966)
  at at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
  at at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
  at at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
  at at android.view.View.layout(View.java:15596)
  at at android.view.ViewGroup.layout(ViewGroup.java:4966)
  at at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:890)
  at at android.view.View.layout(View.java:15596)
  at at android.view.ViewGroup.layout(ViewGroup.java:4966)
  at at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
  at at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
  at at android.view.View.layout(View.java:15596)
  at at android.view.ViewGroup.layout(ViewGroup.java:4966)
  at at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
  at at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
  at at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
  at at android.view.View.layout(View.java:15596)
  at at android.view.ViewGroup.layout(ViewGroup.java:4966)
  at at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
  at at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
  at at android.view.View.layout(View.java:15596)
  at at android.view.ViewGroup.layout(ViewGroup.java:4966)
  at at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
  at at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
  at at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
  at at android.view.View.layout(View.java:15596)
  at at android.view.ViewGroup.layout(ViewGroup.java:4966)
  at at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
  at at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
  at at android.view.View.layout(View.java:15596)
  at at android.view.ViewGroup.layout(ViewGroup.java:4966)
  at at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2072)
  at at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1829)
  at at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
  at at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779)
  at at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
  at at android.view.Choreographer.doCallbacks(Choreographer.java:580)
  at at android.view.Choreographer.doFrame(Choreographer.java:550)
  at at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
  at at android.os.Handler.handleCallback(Handler.java:739)
  at at android.os.Handler.dispatchMessage(Handler.java:95)
  at at android.os.Looper.loop(Looper.java:135)
  at at android.app.ActivityThread.main(ActivityThread.java:5221)
  at at java.lang.reflect.Method.invoke(Native Method)
  at at java.lang.reflect.Method.invoke(Method.java:372)
  at at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by jamesmundy** [comment]
Hey, I'm using Picasso with Xamarin too. I had a huge number of issues initially due to the binding I found being really old. I made my own binding here and it is being used in several apps with no issues: https://github.com/jamesmundy/Xamarin.Picasso

**Comment by escobar5** [comment]
Thanks @jamesmundy, I tried it and it works.
